import base64

def encode_logic(text):
    """Step-by-step: Reverse -> Base85 -> ROT13 -> Hex"""
    # 1. Reverse the string
    step1 = text[::-1]
    # 2. Base85 Encode
    # Note: b85 is picky, so we ensure it's bytes first
    step2 = base64.b85encode(step1.encode('utf-8')).decode('utf-8')
    # 3. ROT13 Shift
    rot13_table = str.maketrans(
        "ABCDEFGHIJKLMabcdefghijklmNOPQRSTUVWXYZnopqrstuvwxyz",
        "NOPQRSTUVWXYZnopqrstuvwxyzABCDEFGHIJKLMabcdefghijklm"
    )
    step3 = step2.translate(rot13_table)
    # 4. Final Hex Conversion
    final_hex = step3.encode('utf-8').hex()
    return final_hex

def decode_logic(hex_str):
    """Step-by-step: Un-Hex -> Un-ROT13 -> Un-Base85 -> Reverse"""
    try:
        # 1. Un-Hex (Convert hex string back to regular string)
        step1 = bytes.fromhex(hex_str).decode('utf-8')
        
        # 2. Un-ROT13 (ROT13 is its own inverse)
        rot13_table = str.maketrans(
            "ABCDEFGHIJKLMabcdefghijklmNOPQRSTUVWXYZnopqrstuvwxyz",
            "NOPQRSTUVWXYZnopqrstuvwxyzABCDEFGHIJKLMabcdefghijklm"
        )
        step2 = step1.translate(rot13_table)
        
        # 3. Un-Base85
        step3 = base64.b85decode(step2.encode('utf-8')).decode('utf-8')
        
        # 4. Un-Reverse
        final_text = step3[::-1]
        return final_text
    except Exception as e:
        return f"[!] Error: {e}. Check if the hex was generated by this specific encoder!"

def main():
    print("--- THE VAULT ENCODER/DECODER ---")
    print("Commands: 1 (Encode), 2 (Decode), 'exit'")
    
    while True:
        choice = input("\nAction > ").strip()
        
        if choice.lower() == 'exit':
            print("Cya! ✌️")
            break
            
        if choice == '1':
            msg = input("Text to hide: ")
            print(f"Hex Result: {encode_logic(msg)}")
            
        elif choice == '2':
            hex_input = input("Hex to decode: ")
            print(f"Decoded: {decode_logic(hex_input)}")
        else:
            print("Just 1, 2, or exit. Don't overthink it.")

if __name__ == "__main__":
    main()